### ISSUE TITLE
USER STORY: Approve/Decline reviews

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#10]
EPIC: Reviews

USER STORY: As a **Site Owner ** I can **manage reviews** so that **I approve/decline them**

**Acceptance Criteria**

- [ ] When a user leaves a review, it is stored in the database waiting for approval
- [ ] When site owner approves, it can be shown on the homepage (if 5 stars and nicely written)
- [ ] Otherwise if approved, it is added to the reviews database
- [ ] If declined, it is removed from the database

**Tasks**
