### ISSUE TITLE
USER STORY: Log activity session

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#11]
EPIC: <epic>

USER STORY: As a **Site User** I can **start a new activity session** so that **I can input activity data**

**Acceptance Criteria**

- [ ] The user can log a new activity session (entering duration, distance and type)

**Tasks**
- [ ] User is redirected to the custom model of activity page
- [ ] User is redirected to the custom model of nutrition page
