### ISSUE TITLE
USER STORY: Set profile targets

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#12]
EPIC: Profile Card - Set targets

USER STORY: As a **Site User** I can **input target weight** so that **I stay on track**

**Acceptance Criteria**

- [x]  user can create target weight
- [x] User can see their target weight
- [x] User can update their target weight

**Tasks**
