### ISSUE TITLE
USER STORY: Dashboard for signed in users

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#13]
EPIC: Authentication

USER STORY: As a **Site Owner** I can **show the dashboard only to authenticated users** so that **users sign up/in**

**Acceptance Criteria**

- [x] When users are not signed in, they only see the home page - no dashboard
- [x] When users are signed in, they can access their dashboard

**Tasks**
- [x] Build the HTML and CSS for the Home page
- [x] Build the HTML and CSS for the Dashboard
