### ISSUE TITLE
USER STORY: Log activity session

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#16]
EPIC: Display data

USER STORY: As a **user** I can **log my activity session** so that **I can track my performance**

**Acceptance Criteria**

- [x] Input new activity session (duration, distance and type
- [x] Display the user's last activity log
- [x] Update activity session
- [x] Delete activity session

**Tasks**
- [x] Retrieve and post data entries from/to the database
- [x] Implement the activity burned API
