### ISSUE TITLE
USER STORY: Log nutrition session

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#18]
EPIC: Logging data

USER STORY: As a **site user** I can **log nutrition session** so that **I track my calorie intake**

**Acceptance Criteria**

- [x] The user can log a new nutrition session (entering food and quantity)
- [x] Display the user's last nutrition session
- [x] Update nutrition session
- [x] Delete nutrition session

**Tasks**
