### ISSUE TITLE
USER STORY: Update profile image

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#21]
EPIC: <epic>

USER STORY: As a **site user** I can **update my profile attributes** so that **it shows on my profile page and used in metrics**

**Acceptance Criteria**

- [x] Update image button on profile page
- [x] Update birth date on profile page
- [x] Update height on profile page

**Tasks**
