### ISSUE TITLE
USER STORY: Create Metrics

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#23]
EPIC: Profile card - Create data

USER STORY: As a **Site User** I can **input my weight and height** so that **I get BMI, metabolic age and  BMR measurements**

**Acceptance Criteria**

- [x] User can input their metrics

**Tasks**
- [x] Create button that allows the user to input the values
- [x] User input has to be numbers only
