### ISSUE TITLE
USER STORY: Access apps and URLs from admin board

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#5]
EPIC: Initialization

USER STORY: As a **Site Owner** I can **connect to Django database** so that **I see apps on admin dashboard**

**Acceptance Criteria**

- [x] I can access the admin board
- [x] I can navigate to the URLs 
- [x] I can see the apps installed and migrated on admin dashboard

**Tasks**
- [x] Install and migrate django-summernote and django-allauth
- [x] Install cloudinary for storing images
- [x] Install whitenoise to serve the static files
