### ISSUE TITLE
USER STORY: Update Metrics

### ISSUE THREAD

**Issue by mtelewa** [mtelewa/fitness-tracker#6]
EPIC: Profile card - Update data

USER STORY: As a **Site User** I can **update my weight and height** so that **I get the current BMI and  BMR measurements**

**Acceptance Criteria**

- [x] User can update their weight and height measures

**Tasks**
- [x] Update button that allows the user to edit the values
- [x] User input has to be numbers only
